### ISSUE TITLE
[Bug Report] Not working hosted on heroku 

### ISSUE THREAD

**Issue by ak-47-brar** [X-Gorn/BulkLoader#10]
[fathomless-savannah-80566-logs-1701685885871.txt](https://github.com/X-Gorn/BulkLoader/files/13544986/fathomless-savannah-80566-logs-1701685885871.txt)

**Comment by xgorn** [comment]
Add heroku ffmpeg buildpack: `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest`
