### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by nottyd** [X-Gorn/BulkLoader#3]
download getting stuck at the same file for so long

**Comment by xgorn** [comment]
send logs and screenshot @REDAKUN

**Comment by nottyd** [comment]
Expected behavior : download all files Found in the text file i sent and start uploading to telegram.
Actual behavior : 
Getting stuck at certain point and stop downloading or even start to upload downloaded files

![ScreenShot_20220226022433](https://user-images.githubusercontent.com/68442725/155824845-80167e96-67ea-495d-aaf0-2e324be2af46.png)


![IMG_20220226_031009](https://user-images.githubusercontent.com/68442725/155825031-9a1d12b3-908d-4966-af06-6db9ee076170.jpg)



Log file : 

https://pixeldrain.com/u/77TJ1LYr

Files that I'm trying to download : 

https://pixeldrain.com/u/1PMfBfxW

@X-Gorn

**Comment by xgorn** [comment]
Your link is died, try it on your browser before sending it to bot

**Comment by nottyd** [comment]
@X-Gorn NAHH everything on my side is working I've tried multiple direct links from all kind of websites 
And still download get stuck at some point

**Comment by xgorn** [comment]
ok, i'll try to fix that
