### ISSUE TITLE
0

### ISSUE THREAD

**Issue by insoxin** [X-Gorn/BulkLoader#4]
0

**Comment by PalashMudi** [comment]
Anyone found Solution?

**Comment by xgorn** [comment]
@PalashMudi Are you deploying the bot using venv? or docker?

**Comment by PalashMudi** [comment]
Created app in heroku and then manualy inputed variable.. working start button, help button also downloading but after downloading, proccessing going vanished.

**Comment by PalashMudi** [comment]
@insoxin Do you resolve it?
