### ISSUE TITLE
#request

### ISSUE THREAD

**Issue by ghost** [X-Gorn/BulkLoader#5]
Will you be add zoom links and M3U8 support
In it

**Comment by xgorn** [comment]
@Enterausername00000 interesting, i'll try that.

**Comment by ghost** [comment]
> @Enterausername00000 interesting, i'll try that.

Thanks for replying sir it will help alot if you do so 🥺🥺🥺🙏🙏

**Comment by xgorn** [comment]
m3u8 supported on latest release, i don't know for zoom links.
